### ISSUE TITLE
math.hpp中Rand()函数不需要调用srand()函数吗？

### ISSUE THREAD

**Issue by icyhearts** [kokerf/vision_kit#1]
查看了math.hpp中 Rand(double min, double max)函数，直接调用rand()函数，调用rand()之前是不是需要调用srand()函数？不然的话，每次生成的随机数都是一样的吧？

**Comment by kokerf** [comment]
@icyhearts  对的，如果需要每次不一样，需要增加srand()的，或者使用c++的随机数生成器。这份代码主要用来验证算法和写一些小工具，所以只用了rand()。
